### ISSUE TITLE
Suggest Configurator

### ISSUE THREAD

**Issue by sharkman79** [radphp/logging#1]
I can suggest to create one configuration file to choose where the file must be write.
It is possible

**Comment by omid** [comment]
Thanks for your suggestion.
Because it is a "library" and it doesn't support configurable files.
But you can load log file path from configuration file in your app, then pass it to adapter:

```php
// Attach single or multiple adapters
$logger = new Logger();

// Load log file path
$logFilePath = '/path/to/file.log';

$logger->attachAdapter(new FileAdapter($logFilePath));

// You can pass message to these log levels
$logger->emergency('Something did not work');
```

Is it what you want?
